name: Build MyLibrary and Copy DLL

on:
  workflow_dispatch:

jobs:
  build-and-copy:
    runs-on: self-hosted

    steps:
      - name: Checkout MyLibrary repo
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Clean MyLibrary VB Project
        run: msbuild MyLibrary.vbproj /t:Clean /p:Configuration=Debug /p:Platform=AnyCPU

      - name: Build MyLibrary VB Project
        run: msbuild MyLibrary.vbproj /p:Configuration=Debug /p:Platform=AnyCPU

      - name: Copy DLL to DemoCodeBasic bin folder
        shell: powershell
        run: |
          $sourceDLL = "${{ github.workspace }}\bin\Debug\MyLibrary.dll"
          $destination = "D:\DemoCodeBasic\DemoCodeBasic\bin\MyLibrary.dll"

          if (Test-Path $destination) {
            Remove-Item $destination -Force
          }

          Copy-Item -Path $sourceDLL -Destination $destination -Force
