name: Build MyLibrary and Copy DLL

on:
  workflow_dispatch:

jobs:
  build-and-copy:
    runs-on: self-hosted

    steps:
      - name: Checkout MyLibrary repo
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Optional: Manually clean bin and obj folders to ensure a truly fresh build
      - name: Clean bin and obj folders manually
        shell: powershell
        run: |
          if (Test-Path "${{ github.workspace }}\bin") {
            Remove-Item -Recurse -Force "${{ github.workspace }}\bin"
          }
          if (Test-Path "${{ github.workspace }}\obj") {
            Remove-Item -Recurse -Force "${{ github.workspace }}\obj"
          }

      - name: Force Build MyLibrary VB Project (ignore timestamps)
        run: msbuild MyLibrary.vbproj /t:Build /p:Configuration=Debug /p:Platform=AnyCPU /p:DisableFastUpToDateCheck=true

      - name: Copy DLL to DemoCodeBasic bin folder
        shell: powershell
        run: |
          $sourceDLL = "${{ github.workspace }}\bin\Debug\MyLibrary.dll"
          $destination = "D:\DemoCodeBasic\DemoCodeBasic\bin\MyLibrary.dll"

          if (Test-Path $destination) {
            Remove-Item $destination -Force
          }

          Copy-Item -Path $sourceDLL -Destination $destination -Force
